local M = {}

M.codes = {
  UNSUPPORTED_NVIM = "E_UNSUPPORTED_NVIM",
  INVALID_ARGUMENT = "E_INVALID_ARGUMENT",
  INVALID_SOURCE_BUFFER = "E_INVALID_SOURCE_BUFFER",
  UNSUPPORTED_FILETYPE = "E_UNSUPPORTED_FILETYPE",
  DOCUMENT_TOO_LARGE = "E_DOCUMENT_TOO_LARGE",
  PARSE = "E_PARSE",
  TRACKING_AMBIGUOUS = "E_TRACKING_AMBIGUOUS",
  ALIGNMENT = "E_ALIGNMENT",
  CONFLICT = "E_CONFLICT",
  STRUCTURE_UNSUPPORTED = "E_STRUCTURE_UNSUPPORTED",
  BACKEND_NOT_FOUND = "E_BACKEND_NOT_FOUND",
  BACKEND_INIT = "E_BACKEND_INIT",
  BACKEND_UNAVAILABLE = "E_BACKEND_UNAVAILABLE",
  BACKEND_PROTOCOL = "E_BACKEND_PROTOCOL",
  BACKEND_AUTH = "E_BACKEND_AUTH",
  BACKEND_RATE_LIMITED = "E_BACKEND_RATE_LIMITED",
  BACKEND_TIMEOUT = "E_BACKEND_TIMEOUT",
  BACKEND_CANCELLED = "E_BACKEND_CANCELLED",
  BACKEND_TOOL_ATTEMPT = "E_BACKEND_TOOL_ATTEMPT",
  BACKEND_INSTRUCTION_SOURCE = "E_BACKEND_INSTRUCTION_SOURCE",
  EPHEMERAL_REQUIRED = "E_EPHEMERAL_REQUIRED",
  TRANSLATION = "E_TRANSLATION",
  INVALID_OUTPUT = "E_INVALID_OUTPUT",
  VALIDATION = "E_VALIDATION",
  STALE_RESULT = "E_STALE_RESULT",
  APPLY_VERSION_MISMATCH = "E_APPLY_VERSION_MISMATCH",
  APPLY = "E_APPLY",
  SESSION_STATE = "E_SESSION_STATE",
  SESSION_CLOSED = "E_SESSION_CLOSED",
  INTERNAL = "E_INTERNAL",
}

function M.new(code, message, retryable, details, cause)
  if type(code) ~= "string" or type(message) ~= "string" then
    error("error code and message must be strings", 2)
  end
  return {
    code = code,
    message = message,
    retryable = retryable == true,
    details = details,
    cause = cause,
  }
end

return M
